name = "shieldcv"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "apps/web/.svelte-kit/cloudflare"

[[r2_buckets]]
binding = "MODELS"
bucket_name = "shieldcv-models"
