// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/version.json",
    "/_app/immutable/*",
    "/favicon.ico",
    "/favicon.svg",
    "/icons/gen-1024/logo.svg.png",
    "/icons/gen-192/logo.svg.png",
    "/icons/gen-512/logo.svg.png",
    "/icons/generated/logo.svg.png",
    "/icons/icon-1024.png",
    "/icons/icon-192.png",
    "/icons/icon-512.png",
    "/icons/icon-maskable-1024.png",
    "/icons/icon-maskable-192.png",
    "/icons/icon-maskable-512.png",
    "/icons/logo.svg",
    "/manifest.webmanifest",
    "/registerSW.js",
    "/sw.js",
    "/trusted-types.js",
    "/workbox-05551db4.js"
  ]
};

// node_modules/.pnpm/wrangler@4.81.1_@cloudflare+workers-types@4.20260411.1/node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "/Users/cam/Projects/shieldcv/.wrangler/tmp/pages-2kejyC/bundledWorker-0.3788079464844758.mjs";
import { isRoutingRuleMatch } from "/Users/cam/Projects/shieldcv/node_modules/.pnpm/wrangler@4.81.1_@cloudflare+workers-types@4.20260411.1/node_modules/wrangler/templates/pages-dev-util.ts";
export * from "/Users/cam/Projects/shieldcv/.wrangler/tmp/pages-2kejyC/bundledWorker-0.3788079464844758.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        const workerAsHandler = worker;
        if (workerAsHandler.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return workerAsHandler.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=nnn9rsgc6k.js.map
